name: rag-llm
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - icu=78.2
  - ld_impl_linux-64=2.45.1
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - liblzma=5.8.2
  - liblzma-devel=5.8.2
  - libnsl=2.0.1
  - libsqlite=3.51.2
  - libstdcxx=15.2.0
  - libuuid=2.41.3
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.6.1
  - packaging=26.0
  - pip=26.0.1
  - python=3.10.14
  - readline=8.3
  - setuptools=82.0.0
  - tk=8.6.13
  - wheel=0.46.3
  - xz=5.8.2
  - xz-gpl-tools=5.8.2
  - xz-tools=5.8.2
  - zstd=1.5.7
  - pip:
      - annotated-types==0.7.0
      - anyio==4.12.1
      - attrs==25.4.0
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - colorcet==3.1.0
      - contourpy==1.3.2
      - cuda-bindings==12.9.4
      - cuda-pathfinder==1.3.4
      - cycler==0.12.1
      - distro==1.9.0
      - docstring-parser==0.17.0
      - eval-type-backport==0.3.1
      - exceptiongroup==1.3.1
      - faiss-cpu==1.8.0.post1
      - filelock==3.21.0
      - fire==0.7.1
      - fonttools==4.61.1
      - fsspec==2026.2.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.2
      - idna==3.11
      - invoke==2.2.1
      - jinja2==3.1.6
      - jiter==0.13.0
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - markupsafe==3.0.3
      - matplotlib==3.7.3
      - mistral-common==1.9.1
      - mistral-inference==1.6.0
      - mistralai==0.4.2
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==1.25.2
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.4.5
      - nvidia-nvtx-cu12==12.8.90
      - openai==2.7.1
      - orjson==3.10.18
      - pandas==2.0.3
      - pillow==12.1.1
      - pycountry==24.6.1
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-extra-types==2.11.0
      - pyparsing==3.3.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - rank-bm25==0.2.2
      - rapidfuzz==3.14.3
      - referencing==0.37.0
      - regex==2026.1.15
      - requests==2.32.5
      - rpds-py==0.30.0
      - safetensors==0.7.0
      - seaborn==0.13.2
      - simple-parsing==0.1.8
      - six==1.17.0
      - sniffio==1.3.1
      - sympy==1.14.0
      - termcolor==3.3.0
      - tiktoken==0.12.0
      - tokenizers==0.19.1
      - torch==2.10.0
      - tqdm==4.67.3
      - transformers==4.42.0
      - triton==3.6.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==2.6.3
      - xformers==0.0.34
